CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `persistent_logins`;
CREATE TABLE `persistent_logins` (
	`username` varchar(64) DEFAULT NULL,
	`series` varchar(64) NOT NULL,
	`token` varchar(64) DEFAULT NULL,
	`last_used` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`series`)
	);
	
DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` (
	`id` varchar(255) NOT NULL,
	`email` varchar(255) DEFAULT NULL,
	`password` varchar(255) DEFAULT NULL,
	`name` varchar(255) DEFAULT NULL,
	`age` int(11) DEFAULT NULL,
	`gender` varchar(2) DEFAULT NULL,
	PRIMARY KEY (`id`)
	);
	
DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` (
	`id` varchar(255) NOT NULL,
	`email` varchar(255) DEFAULT NULL,
	`password` varchar(255) DEFAULT NULL,
	`name` varchar(255) DEFAULT NULL,
	`age` int(11) DEFAULT NULL,
	`gender` varchar(2) DEFAULT NULL,
	PRIMARY KEY (`id`)
	);

DROP TABLE IF EXISTS `Advertiser`;
CREATE TABLE `Advertiser` (
	`id` varchar(255) NOT NULL,
	`name` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`id`)
	);
	
DROP TABLE IF EXISTS `Advertisement`;
CREATE TABLE `Advertisement` (
	`id` varchar(255) NOT NULL,
	`message` varchar(255) DEFAULT NULL,
	`start_age` int(11),
	`end_age` int(11),
	`gender` varchar(5),
	`bid` int(11),
	`budget` int(11),
	`advertiser_id` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`id`)
	);
	